import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AppProvider } from './context/cotext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <form name="contact" data-netlify netlify-honeypot="bot-field" hidden>
      <input autoComplete='on' type="text" name="name" />
      <input autoComplete='on' type="email" name="email" />
      <textarea name="message"></textarea>
      </form>
      <AppProvider>
        {children}
      </AppProvider>
      </body>
    </html>
  )
}
